### ISSUE TITLE
UI: Auto open map on true seeing and read tracks (Bobdiggler)

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/MedievaLandsPublic#348]
Question - this is different functionality compared to the rest of the game. No other skill opens a window. Is this acceptable?

**Comment by evilevilbob** [comment]
I think it just makes sense, as these 2 skills effects can't be observed without opening the map. so you always have to go into the spellbook/skill list, cast, then close it, then open the map. This would just cut out the middle-man required to see the effect of the skill/spell in action.

**Comment by ZaneDubya** [comment]
This is in. :)
