### ISSUE TITLE
Client/Server data exchange: Map Discovery is Persistent between Installs

### ISSUE THREAD

**Issue by rbodor** [ZaneDubya/MedievaLandsPublic#377]
Ability for map discovery to be stored server side, allowing status to follow account vs device

**Comment by ZaneDubya** [comment]
Data:
- Each automap is 800 bytes. There are 34 maps. That's about 27kb.
- The average save size of a single player mobile is currently about 300 bytes.
- The client is responsible for updating the automap, not the server.

Thoughts:
- Would this increase the load on the server when serializing/deserializing the data during world save/load? 27kb doesn't sound like a lot, but it would increase the total save size by 90x.
- Would this increase the total network traffic? It would be an additional single packet of 804 bytes each way for each map. That's a significant packet but not out of line with regards to the size of a SmsgUpdateMobiles packet on entering a crowded map.
- Would this allow the player to cheat by manipulating their automap data in memory? Probably not, and do I really care if people are cheating their automaps??

The biggest concern for me is the save/load burden, followed distantly by network traffic burden. I also need to consider the time required to implement.

Are these outweighed by the benefit to the players? How many players use multiple computers?

**Comment by rbodor** [comment]
Zane,
I apologize for the delay.   That is an excellent point, data size is small
but relative to the current bandwidth, it's a significant jump.   Of course
the other piece is the number of users, is the server set to limit to a
certain number of clients, and is the server load balancing with others?

Thoughts on if the data is written just when a person logs off, where the
map refresh happens twice, on log in (to update from the server) and then
log off to write back?  Would need to consider disconnects too, and
possibly writing back the map data on map changes throughout the session.

all and all may not be worth it, if a user uninstalls the game and
re-installs (say for an update, etc..) are the maps lost?

**Comment by ZaneDubya** [comment]
Hmmmmmmmmmm.... I like the idea of only updating the automap file on login/logout. I'd ignore unplanned disconnects. Although then we're talking about a 27kb packet instead of a 800b packet. Is it possible my network system would break under the strain of such a fat bit of data? I'm not much a programmer. Who knows how close to the breaking point most of this code is.

**Comment by ZaneDubya** [comment]
This will be in the next patch. Maps are compressed before send to the server, and decompressed on receipt by the client. Total map size per game is only 3kb.
