### ISSUE TITLE
Add character-specific bank in Keep

### ISSUE THREAD

**Issue by jerryblade** [ZaneDubya/MedievaLandsPublic#461]
It would be awesome to be able to share gear / gold / items with your other characters. Anything non-trade-able should be prohibited, but all of that stuff that drops that my characters either cannot user or is too weak would be great in gearing up my other toons!

**Comment by ZaneDubya** [comment]
Also:
- [ ] shop tooltips - see item info before buying it.

**Comment by ZaneDubya** [comment]
I am not going to add a shared bank - it would involve a new state object for each game, and the implementation would be too complicated a feature at this time.

But I am working on a bank. Here is a draft in game.

**Comment by ZaneDubya** [comment]
<img width="986" alt="Screen Shot 2020-08-20 at 9 12 16 PM" src="https://user-images.githubusercontent.com/7041719/90844692-1e050b00-e32a-11ea-98ac-061ac192b462.png">

**Comment by ZaneDubya** [comment]
Almost done...

**Comment by ZaneDubya** [comment]
I want to add some icon slot identifiers to the equipment slots, and then I'm good to go!

**Comment by ZaneDubya** [comment]
Done.
