### ISSUE TITLE
Mechanics: Clarity on effectiveness of spell damage.

### ISSUE THREAD

**Issue by HeofHIShirts** [ZaneDubya/MedievaLandsPublic#692]
Playing MedievaLands compared to the original games forced me to rethink some of my older strategies that I had used as a solo player to effectively get places in the dungeons, so I am curious about how the mechanics work now.

For example, in the original Yserbius, Poison Cloud at maximum level was remarkably good at leveling entire groups of enemies in a few turns at most, and this made it remarkably effective for solo play as an inexpensive spell to cast and work while one's Shield was keeping someone alive. In Medievalands, Shield often runs out once or twice before Poison Cloud is done wracking its way through groups. For fights where Shield can absorb all the incoming damage, that's inconvenient to have to spend additional rounds waiting for it to do the work, but for fights where it can't, players can sometimes die from the overage or from being critical-hit by the enemy while they wait for Poison Cloud to do its work.

Additionally, the original game was unclear about whether damage done to "all enemies" or a group of enemies was "this is the total damage done by the spell, split across all the enemies in the affected group" or "each enemy in the group received this much damage from the spell". In Medievalands, it seems to be the first option, while it might have been the second in the original, making all-target spells like Hail and Death Darts more effective at immediately thinning the ranks of the opposition and turning a fight that could be a problem into something more manageable. If the game is supposed to work on the first option, spellcasting damage quickly becomes outpaced by the increased damage and hit points of deeper dungeon levels, making solo play extra difficult unless one has chosen a character that excels at dishing out a lot of weapon damage, so as to defeat the opposition before their defensive magic + HP runs out.

One of the worst parts of both games is the difficulty spike for solo play that happens in the transition between the upper half and the lower half of each dungeon, necessitating severe grinding for a solo player just to advance a small part of the underlying plot, sometimes with a character that has maxed-out statistics and is grinding levels for the opportunity to put enough points into spells and skills so that they might be able to get lucky against whichever scripted fight is in their way. Since those decisions can't be reversed and there's no mechanic to refund and redistribute spell and skill points, having absolute clarity on what damage spells do to opponents (or how much damage absorbed and/or skill bonuses are granted from defensive magics) is crucial for players who may want to experience the game and may never party up at all.

**Comment by ZaneDubya** [comment]
Hi Alex! Thanks for your detailed write up. I enjoyed thinking about this and diving back into the code to answer your questions.

Let me speak to your second point first: there is no concept of individual monsters in either MedievaLands or the original Yserbius. Instead, each monster stack is treated as a single individual monster for all purposes except damage calculation (which I mentioned in the 'combat mechanics' Friday fix article here: https://medievalands.com/news/#20200214-physical-attack-mechanics.txt) and healing (a monster stack's maximum hp is its template hp multiplied by its current 'count' - the numeric variable reflected in its tile in the combat screen). With that in mind, I would phrase the way that damage is done as such: 

> Damage, in both physical and spell attacks, is applied as a single value which reduces the monster stack's total hp. The monster stack's current count is then reduced if its total hp is less than (count-1)*template hp. Spells that target a 'single monster' never cause more damage than would be required to reduce the stack by 1 count.

        /// <summary>
        /// Applies damage to a monster stack, reducing the stack's count as appropriate.
        /// Paramter dmg is negative if we are doing damage, positive if we are healing.
        /// </summary>
        public void AdjustHealth(int dmg, out int killCount) {
            killCount = 0;
            if (IsDead) {
                return;
            }
            int newHealth = _HealthTotalHidden + dmg;
            int currentCount = _CurrentCount;
            if (newHealth <= 0) {
                killCount = _CurrentCount;
                _CurrentCount = 0;
                return;
            }
            int newCount = (newHealth / _TemplateHealthPerMonster) + ((newHealth % _TemplateHealthPerMonster > 0) ? 1 : 0);
            if (newCount > currentCount) {
                newCount = currentCount;
                newHealth = currentCount * _TemplateHealthPerMonster;
            }
            killCount = _CurrentCount - newCount;
            _CurrentCount = newCount;
            _HealthTotalHidden = newHealth;
        }

        /// <summary>
        /// Applies damage to a monster stack, capped at the amount of damage necessary to reduce the stack count by 1.
        /// Paramter dmg is negative if we are doing damage, positive if we are healing.
        /// </summary>
        public void AdjustHealthSingle(int dmg, out int killCount) {
            killCount = 0;
            if (IsDead) {
                return;
            }
            // make sure damage inflicted does not exceed the total health per monster:
            if (dmg < 0 && (-dmg > _TemplateHealthPerMonster)) {
                dmg = -_TemplateHealthPerMonster;
            }
            // now inflict the damage!
            AdjustHealth(dmg, out killCount);
        }

By the way, your point that spell damage becomes outpaced by increasing monster health and monster resistance is absolutely right, and one of the reasons that most high level players in the original game were orc or troll knights. I touched on this in the 'Is Yserbius a class-based game' Friday fix article here: https://medievalands.com/news/#20200207-classes.txt

**Comment by ZaneDubya** [comment]
On your question about poison cloud, I can verify from the original game that the most damage that poison cloud will ever do in a single turn to a single monster stack is 200 damage. You can see this value, which was deobfuscated from the original Yserbius data files, at line 133 of this file: https://github.com/ZaneDubya/YserbiusData/blob/master/Yserbius/Data/Spells.csv.

In the original game, this is applied once per stack, not once per count of a stack.

Unlike the original game, you can re-up your shield at any time. I advocate for this as a tactic to prevent overage ;)
