### ISSUE TITLE
[Crash] Client crash on USB audio change 

### ISSUE THREAD

**Issue by 8byteGaming** [ZaneDubya/MedievaLandsPublic#740]
Game will either crash or "jumble n static" up the audio when switching from monitor speakers to USB headphones. Starting the game with headphones on does not cause this issue, only when switching.

W10 Pro Version 10.0.17763 1809 (OS Build 17763.1158), not activated
Nvidia 2080ti 11GB (Nvidia graphics version 445.87 in control panel)
32GB "OC" from 2333Mhz to 3600Mhz Patriot RAM
SSD Sabrent Rocket NVMe M.2 2280 1TB
3900x R9 12-core AMD OC from 3.8Ghz to 4.2Ghz
MSI MEG X570 ACE Motherboard, BIOS Version/Date: American Megatrends Inc. 1.70, 11.6.2019

**Comment by ZaneDubya** [comment]
Hey @8byteGaming, unfortunately, the FNA library does not support hot switching of audio outputs. I will add something to the help page about this.

Best,

Zane
