### ISSUE TITLE
[UI Bug] The player icon UI health bar does not update after battle

### ISSUE THREAD

**Issue by 8byteGaming** [ZaneDubya/MedievaLandsPublic#741]
After a battle ends and you use a magic heal spell; when healing, the UI bar for mana does not decrease. I think this is only on the first use after a battle.

**Comment by ZaneDubya** [comment]
Needs investigation.

**Comment by ZaneDubya** [comment]
Fixed!

**Comment by ZaneDubya** [comment]
In next patch, ready to deploy.
