### ISSUE TITLE
CommunityClient just exits

### ISSUE THREAD

**Issue by pchernik** [ZaneDubya/MedievaLandsPublic#745]
I've just downloaded the CommunityClient and trying to run it on my Windows 10 computer.

It starts up, installs to Documents\Games\CommunityKit\CommunityClient.app, then I see the following screen:
Checking for application updates...
    Application is up to date!
Checking for resource file updates...
    Resource files up to date. Ready to play!

It sits on this screen for a couple of seconds and just exits out.

I tried running with admin privileges, and tried compatibility modes of windows 7 and 8 - same result.

The following is in the log:
```
Debug:     Resolution Info:
Debug:         Screen=2560x1440
Debug:         HiDPI=1
Debug:         MaxScale=3.933333
Debug: ModeLoading initializing.
Debug:     Platform is: 1
Debug:     Running in:  C:\Users\pcher\OneDrive\Documents\Games\CommunityKit\CommunityClient.app\
Debug:     PathExeDir:  C:\Users\pcher\OneDrive\Documents\Games\CommunityKit\CommunityClient.app
Debug:     FilenameExe: CommunityClient.exe
Debug:     ForceUpdate: False
Debug: Platform.RunningBuildID = C:\Users\pcher\OneDrive\Documents\Games\CommunityKit\CommunityClient.app\build-id.txt
Debug:     Running ID:  5248926307313767835
Debug: Platform.LocalBuildID = C:\Users\pcher\OneDrive\Documents\Games\CommunityKit\CommunityClient.app\build-id.txt
Debug:     Local ID:    5248926307313767835
Debug: 
Debug: ModeLoading: Checking for application updates...
Debug: Attempting to read remote build id...
Debug:     Success! Remote Build ID = 5248580201218806376
Debug: Attempting to read remote build id...
Debug:     Success! Remote Build ID = 5248926307313767835
Debug: ModeLoading:     Application is up to date!
Debug: ModeLoading: Checking for resource file updates...
Debug: ModeLoading:     Resource files up to date. Ready to play!
Debug: ModeLogin Initializing...
Debug: FileSystem loaded successfully at C:\Users\pcher\OneDrive\Documents\Games\CommunityKit\Resources
Debug: ASound ctor [Audio\Legacy\128-Theme.mp3]
```

Help!

**Comment by ZaneDubya** [comment]
Interesting! I haven't seen this bug before.

You've uploaded a patch log. There may be other logs in the same folder that may indicate an error. Would you please check in the other log files?

Thanks, Zane

**Comment by pchernik** [comment]
Hey Zane. Thanks for the reply. I don't see any other logs anywhere:

`C:\Users\pcher\OneDrive\Documents\Games\CommunityKit>dir/s
 Volume in drive C has no label.
 Volume Serial Number is 3EC4-DD6E

 Directory of C:\Users\pcher\OneDrive\Documents\Games\CommunityKit

06/13/2020  03:14 PM    <DIR>          .
06/13/2020  03:14 PM    <DIR>          ..
06/13/2020  03:14 PM    <DIR>          CommunityClient.app
06/15/2020  09:24 AM    <DIR>          Logs
06/15/2020  09:24 AM    <DIR>          Resources
               0 File(s)              0 bytes

 Directory of C:\Users\pcher\OneDrive\Documents\Games\CommunityKit\CommunityClient.app

06/13/2020  03:14 PM    <DIR>          .
06/13/2020  03:14 PM    <DIR>          ..
06/13/2020  03:14 PM                19 build-id.txt
06/13/2020  03:14 PM           896,664 CommunityClient.exe
06/13/2020  03:14 PM               277 CommunityClient.exe.config
06/13/2020  03:14 PM    <DIR>          Content
06/13/2020  03:14 PM           284,469 FAudio.dll
06/13/2020  03:14 PM           879,104 FNA.dll
06/13/2020  03:14 PM             1,100 FNA.dll.config
06/13/2020  03:14 PM           347,272 libtheorafile.dll
06/13/2020  03:14 PM           175,025 MojoShader.dll
06/13/2020  03:14 PM           160,256 MP3Sharp.dll
06/13/2020  03:14 PM            22,696 PatcherWin.exe
06/13/2020  03:14 PM         1,088,000 SDL2.dll
06/13/2020  03:14 PM           205,458 SDL2_image.dll
              12 File(s)      4,060,340 bytes

 Directory of C:\Users\pcher\OneDrive\Documents\Games\CommunityKit\CommunityClient.app\Content

06/13/2020  03:14 PM    <DIR>          .
06/13/2020  03:14 PM    <DIR>          ..
06/13/2020  03:14 PM             2,256 Fonts.bin
06/13/2020  03:14 PM             1,202 TextEffect.xnb
06/13/2020  03:14 PM             1,438 UpscaleEffect.xnb
               3 File(s)          4,896 bytes

 Directory of C:\Users\pcher\OneDrive\Documents\Games\CommunityKit\Logs

06/15/2020  09:24 AM    <DIR>          .
06/15/2020  09:24 AM    <DIR>          ..
06/15/2020  09:24 AM             1,424 log-2020-06-15-09-24-21.txt
               1 File(s)          1,424 bytes

 Directory of C:\Users\pcher\OneDrive\Documents\Games\CommunityKit\Resources

06/15/2020  09:24 AM    <DIR>          .
06/15/2020  09:24 AM    <DIR>          ..
04/26/2020  10:48 PM         2,255,440 cano-client.lpk
04/26/2020  10:48 PM            15,901 cano-patch.lpk
04/26/2020  10:48 PM           138,389 cano.lpk
06/13/2020  03:14 PM         1,940,976 common-client.lpk
04/26/2020  10:48 PM             9,939 common.lpk
06/15/2020  09:24 AM               280 manifest.csv
04/26/2020  10:48 PM         8,115,843 sound-effects.lpk
04/26/2020  10:48 PM        45,158,039 sound-music.lpk
               8 File(s)     57,634,807 bytes
`

**Comment by alerum68** [comment]
Possible conflict from running from a Cloud linked folder? Try reinstalling to another folder outside of OneDrive?

**Comment by ZaneDubya** [comment]
This is interesting. I think @alerum68 may have the right idea. Unfortunately, the user doesn't have a choice as to where the game is installed - it just runs from your documents folder. :(

@pchernik Please confirm - you downloaded the client (to, for example, your downloads folder). When you run the client in that location, it tells you that the client will restart in your documents folder. Then it closes - and nothing else happens?

**Comment by pchernik** [comment]
@ZaneDubya that's right, it copies files to documents\games folder, restarts, downloads updates, then says "Ready to play!" - then hangs there for a few seconds, and exits.

**Comment by pchernik** [comment]
I've changed location of Documents to a non-OneDrive location, reran CommunityClient.exe, and got exactly same result.

```
Debug:     Resolution Info:
Debug:         Screen=2560x1440
Debug:         HiDPI=1
Debug:         MaxScale=3.933333
Debug: ModeLoading initializing.
Debug:     Platform is: 1
Debug:     Running in:  C:\Users\pcher\Documents\Games\CommunityKit\CommunityClient.app\
Debug:     PathExeDir:  C:\Users\pcher\Documents\Games\CommunityKit\CommunityClient.app
Debug:     FilenameExe: CommunityClient.exe
Debug:     ForceUpdate: False
Debug: Platform.RunningBuildID = C:\Users\pcher\Documents\Games\CommunityKit\CommunityClient.app\build-id.txt
Debug:     Running ID:  5248926307313767835
Debug: Platform.LocalBuildID = C:\Users\pcher\Documents\Games\CommunityKit\CommunityClient.app\build-id.txt
Debug:     Local ID:    5248926307313767835
Debug: 
Debug: ModeLoading: Checking for application updates...
Debug: Attempting to read remote build id...
Debug:     Success! Remote Build ID = 5248580201218806376
Debug: Attempting to read remote build id...
Debug:     Success! Remote Build ID = 5248926307313767835
Debug: ModeLoading:     Application is up to date!
Debug: ModeLoading: Checking for resource file updates...
Debug: ModeLoading:     Resource files up to date. Ready to play!
Debug: ModeLogin Initializing...
Debug: FileSystem loaded successfully at C:\Users\pcher\Documents\Games\CommunityKit\Resources
Debug: ASound ctor [Audio\Legacy\128-Theme.mp3]
```

**Comment by pchernik** [comment]
I've captured the process here: [https://www.youtube.com/watch?v=EKh5pQr0KO8&feature=youtu.be](url)

**Comment by ZaneDubya** [comment]
Thanks for the log and the video, @pchernik. As you know, I'm just a hobby developer, so bugs like this, although frustrating, are understandable. Thanks for helping me troubleshoot this.

Your video and log files have ruled out many possible errors, but unfortunately I still do not know why this is happening. If the program crashes due to an internal error, then it should report an exception in the log files. Yet I see that is not happening.

I can see that the game's internal file system and graphics framework is working. I don't think it is crashing due to file access or texture creation. Interestingly, the last message is from the audio system. So I believe there may be a problem loading audio.

Would you please trouble shoot this by creating a new folder named 'Settings' in your Documents/Games/CommunityKit/ folder (the same folder where you'll find the CommunityKit.app, Logs, and Resources folders). In that folder, create a new file called 'settings.xml'. You can use notepad to create that file. Paste this text into that file to disable music and sound effects:

<?xml version="1.0" encoding="utf-8" standalone="yes"?><settings accountName="" sfxOn="False" sfxVolume="80" musicOn="False" musicVolume="0" soundtrackNew="True" helpPrompts="0" newScaleFactor="1" dungeonChatModal="False" />

**Comment by pchernik** [comment]
Hey Zane. I understand what you mean all too well and I really appreciate the help! Thank you!

The game starts up with the settings you provided that disable sound and music.

**Comment by ZaneDubya** [comment]
Neat! Glad to hear it is working, absent the audio. 

Can you think of any way in which your audio set up might be out of the ordinary?

**Comment by pchernik** [comment]
I'm using Sound Blaster X3 to connect from my gaming laptop to my 5.1 system, I wonder if that has something to do with that.
https://us.creative.com/p/sound-blaster/sound-blaster-x3

**Comment by ZaneDubya** [comment]
If the game is now working, then it might be some kind of mismatch between my audio library (FNA/FAudio) and the SoundBlaster peripheral driver.

But I can't say. Very strange!

Do you see anything interesting in this log file?

1. Type %TEMP% into the Windows Explorer address bar.
2. Scroll down the list and look for creative-sbcommand-log-file.txt.

**Comment by pchernik** [comment]
There are no files under %TEMP% that start with creative*.

Also, I unplugged sound blaster usb cable, and tried running with just the regular speaker as output - same result.

**Comment by pchernik** [comment]
I've checked the windows application event viewer and I see the following there:
```
Fault bucket 1298401551379296370, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: CommunityClient.exe
P2: 0.9.7427.18243
P3: 5ead8cd8
P4: SDL2.DLL
P5: 2.0.9.0
P6: 00000000
P7: c0000005
P8: 00062516
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4D06.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4E40.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4E50.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4E5E.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER4E7E.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_CommunityClient._5a92cecf9ddea656b24cb99e3a23375cb8cf746_1e12520b_b01b27ec-6bc1-41e0-a4e3-38874bd54977

Analysis symbol: 
Rechecking for solution: 0
Report Id: d2d6a740-79c3-4658-86bd-7a27a6015f0d
Report Status: 268435456
Hashed bucket: 497536dd127e9471b204d954edc77072
Cab Guid: 0
```
The .wer file is attached below:
[Report.wer.txt](https://github.com/ZaneDubya/MedievaLandsPublic/files/4788139/Report.wer.txt)

**Comment by ZaneDubya** [comment]
Thanks! It looks like the crash was in the SDL dll used by my version of FNA.

Unfortunately, I can't say exactly what caused the crash.

At some point in the future I'll be upgrading my version of FNA. I'll ping you when I do. :)

**Comment by pchernik** [comment]
Understood. Thanks for helping me with the issue and providing guidance on getting the game started.

**Comment by ZaneDubya** [comment]
Send me an email at hello@medievalands.com and I'll forward you some music to put on repeat ;)

**Comment by ZaneDubya** [comment]
Hey @IceKickr, I've updated the FNA library, but I don't think this will solve your issue. :(

**Comment by IceKickr** [comment]
Hey Zane - just tried it out - still same issue. Thanks for looking into this, don't worry about it - as it seems to be some sort of very corner case.

**Comment by ZaneDubya** [comment]
I agree, but it's still a bummer! I've asked around the FNA developer community (there's a surprisingly large member count!) and they have also had issue with USB support, but it is sporadic and hard to nail down even for full time indie studios. :(

I'll keep your use case in mind as I continue to develop this, and will ping you again if I think anything may have changed on this front.

Take care!
